# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf56857a5b6494083ece8d73c5c01a67497217234e763798a23b16644a4f5b9dda262e654d8ead1a8def600bf0515773b89874227f614a33ddffc46bc0a11177

test:
  secret_key_base: 5096400411a673aac56ea48f894cac09e25853f948c936547ff54987d9bebd1cc0824e55166c14f0fd52c0440eddd81f954e5d6a6b1312810c8b8c0d35207ed3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
